### ISSUE TITLE
wu 

### ISSUE THREAD

**Issue by xiezhancheng** [gefei-hao/RDFL#1]

**Comment by gefei-hao** [comment]
Thank you for your interest in our job. This mistake looks like the Padel-Descriptor did not give the right result for further prediction. You can check whether the Padel is well installed. The link&nbsp;http://www.yapcwsoft.com/dd/padeldescriptor/&nbsp;might be helpful to you.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gefei-hao/RDFL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月30日(星期二) 下午2:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[gefei-hao/RDFL] 输出错误 (Issue #1)





 
(xzc) ***@***.***:-/xzcRDFL-master/RFLS python RFL.py example. smi score.txt
 Traceback (most recent call last):
 File "RFL.py". line 29, in 
 with open("-/PaDEL OUT.csv) as f:
 FileNotFoundError:[Errno 2] NO such flle or directory:'. /PaDEL OUT.csv '

**Comment by xiezhancheng** [comment]
Thank you for your response. I would also like to inquire about the reasons behind obtaining zero calculation results for certain structures. ---- Replied Message ***@***.***>Date01/31/2024 10:55 ***@***.***> ***@***.***>,State ***@***.***>SubjectRe: [gefei-hao/RDFL] wu (Issue #1)
Thank you for your interest in our job. This mistake looks like the Padel-Descriptor did not give the right result for further prediction. You can check whether the Padel is well installed. The link&nbsp;http://www.yapcwsoft.com/dd/padeldescriptor/&nbsp;might be helpful to you.&nbsp;









------------------&nbsp;原始邮件&nbsp;------------------

发件人:                                                                                                                        "gefei-hao/RDFL"                                                                                    ***@***.***&gt;;

发送时间:&nbsp;2024年1月30日(星期二) 下午2:39

***@***.***&gt;;

***@***.***&gt;;

主题:&nbsp;[gefei-hao/RDFL] 输出错误 (Issue #1)











 

(xzc) ***@***.***:-/xzcRDFL-master/RFLS python RFL.py example. smi score.txt

 Traceback (most recent call last):

 File "RFL.py". line 29, in 

 with open("-/PaDEL OUT.csv) as f:

 FileNotFoundError:[Errno 2] NO such flle or directory:'. /PaDEL OUT.csv '

 

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/gefei-hao/RDFL/issues/1#issuecomment-1918288760",
"url": "https://github.com/gefei-hao/RDFL/issues/1#issuecomment-1918288760",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
